### ISSUE TITLE
When browser is maximized FitToScreenAction cuts parts of the diagram

### ISSUE THREAD

**Issue by planger** [eclipsesource/icat#42]
Interestingly, the `FitToScreenAction` works perfectly, when the browser is not maximized. If the browser is maximized, some parts are cut out.

I guess there is something wrong with the viewpoint computation.

**Comment by eneufeld** [comment]
The problem is a bug in https://github.com/eclipse/sprotty/blob/579bee34577f2243a36fc178c6bef9debc9116ea/src/features/viewport/center-fit.ts#L200

While this is not fixed, we can set the padding to undefined.
