### ISSUE TITLE
Escape class names in Web Docu

### ISSUE THREAD

**Issue by planger** [eclipsesource/icat#61]
If an ecore class has an attribute `header` the web docu doesn't work anymore and the following error message occurs: „Duplicated ID <classname>_header“

**Comment by eneufeld** [comment]
Problem is in GLSP-Ecore. See Commit https://github.com/eclipsesource/ecore-glsp/commit/f7f1e0bb4249d4d175218f3700bcc3fdc287bc0a

**Comment by planger** [comment]
Integrated and fixed with https://github.com/eclipsesource/icat/commit/aa3ed49436f2558dbbdd2fdc36558169e1b48f12
